### ISSUE TITLE
little mistake in calculations

### ISSUE THREAD

**Issue by const-dominik** [Ph0enixKM/AiSD-Dla-Opornych#1]
Hello, don't know if you're updating these, but I found a little mistake while making my own notes, studying from yours. 

https://github.com/Ph0enixKM/AiSD-Dla-Opornych/blob/master/5%20Dolna%20Granica.pdf

In summary of the adversary problem:
![image](https://github.com/user-attachments/assets/a9bdb2fb-bf4e-4c42-a2a8-82586b0f3066)

That's ceil(5n/2 - 2), and it should be ceil(3n/2-2) - finding max in B and minimum in C won't take n-1 each, |B| + |C| = n, and finding max and min is |B| - 1 and |C| - 1 respectively, which adds up to n-2 and fixes the calculations.

**Comment by Ph0enixKM** [comment]
Good catch! I'll fix this asap. If you found any other errors, let me know. Thank you for your feedback! 🙏

**Comment by Ph0enixKM** [comment]
@const-dominik just uploaded the fix. Can you make a quick review?

**Comment by const-dominik** [comment]
@Ph0enixKM Thanks for quick response on this issue. To be super precise, calculations now add up to 3n/2 - 1.  Comparisons that are needed to find max are n/2 - 1 rather than (n-1)/2, same for finding minimum.

**Comment by Ph0enixKM** [comment]
Oh yeah. Sorry for that. That was clearly incorrect. Just patched it. You can find the update file [here](https://github.com/Ph0enixKM/AiSD-Dla-Opornych/blob/79a41f67c78a6ec84011eb5da17c8340be17f858/5%20Dolna%20Granica.pdf).

**Comment by Ph0enixKM** [comment]
@const-dominik does it look right now?

**Comment by const-dominik** [comment]
@Ph0enixKM looks perfect to me! Thanks for your effort and cheers for your great notes :D

**Comment by Ph0enixKM** [comment]
Thanks so much! I'm glad that you found them helpful. Good luck on your exam :D 🤞
